# Generated by Django 4.0.4 on 2022-05-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('photo_extrait', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('contenu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_paragraphe', models.TextField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('photo_cours', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.domaine')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
    ]
