# Generated by Django 4.0.4 on 2022-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_name',
            field=models.ImageField(height_field=100, null=True, upload_to='photos/users_picture', width_field=100),
        ),
    ]
