# Generated by Django 4.0.4 on 2022-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='field_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos/users_picture'),
        ),
    ]
