# Generated by Django 4.0.4 on 2022-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphe',
            name='have_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paragraphe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/chapitre/'),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('paragraphes', models.ManyToManyField(blank=True, null=True, related_name='choices', to='users.paragraphe')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='chpitres',
            field=models.ManyToManyField(blank=True, null=True, related_name='choices', to='users.chapitre'),
        ),
    ]
