# Generated by Django 4.0.4 on 2022-06-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_paragraphe_have_image_paragraphe_image_chapitre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='chpitres',
            new_name='chapitres',
        ),
    ]
