# Generated by Django 4.0.4 on 2022-06-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_cours_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='forum',
        ),
        migrations.AddField(
            model_name='cours',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='users.post'),
        ),
    ]
