# Generated by Django 4.0.4 on 2022-06-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_cours_forum_cours_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='forum',
        ),
        migrations.AddField(
            model_name='post',
            name='cour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.cours'),
            preserve_default=False,
        ),
    ]
