# Generated by Django 4.0.4 on 2022-06-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_post_cour_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.forum'),
            preserve_default=False,
        ),
    ]
