# Generated by Django 4.0.4 on 2022-06-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
