# Generated by Django 4.0.4 on 2022-06-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_post_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.cours')),
            ],
        ),
    ]
