# Generated by Django 4.0.4 on 2022-06-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_post_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
