# Generated by Django 4.0.4 on 2022-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_cours_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paragraphe',
            name='titre_paragraphe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
