# Generated by Django 4.0.4 on 2022-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users_picture/default.png', upload_to='users_picture'),
        ),
    ]
