# Generated by Django 4.0.4 on 2022-06-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_friend_remove_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
