# Generated by Django 4.0.4 on 2022-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_friend_chatmessage_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='etat',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
