# Generated by Django 4.0.4 on 2022-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFriend',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
