# Generated by Django 4.0.4 on 2022-06-26 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0044_cours_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
