# Generated by Django 4.0.4 on 2022-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_cours_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postBlock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isFriend',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
