# Generated by Django 4.0.4 on 2022-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_paragraphe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphe',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
