# Generated by Django 4.0.4 on 2022-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_paragraphe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isFriend',
            field=models.BooleanField(default=True),
        ),
    ]
