# Generated by Django 4.0.4 on 2022-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_paragraphe_image_alter_profile_isfriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField()),
            ],
        ),
    ]
