# Generated by Django 4.0.4 on 2022-06-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='etat',
            field=models.BooleanField(blank=True),
        ),
        migrations.CreateModel(
            name='VideoCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=100)),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cours')),
            ],
        ),
    ]
