# Generated by Django 4.0.4 on 2022-06-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_stream_etat_videocours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocours',
            name='cour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cours'),
        ),
    ]
