# Generated by Django 4.0.4 on 2022-06-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_cours_pdf'),
        ('quiz', '0002_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('reponse', models.CharField(max_length=100)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.cours')),
            ],
        ),
    ]
