# Generated by Django 4.0.4 on 2022-06-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_friend_chatmessage_profile_friends'),
        ('quiz', '0004_delete_question_alter_questions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.cours'),
        ),
    ]
